action_id: trunk-whoami
date: 2025-07-19 16:23:25
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1752942205
full_timestamp:
  nanos: 685325000
  seconds: 1752942205
trunk_version: 1.24.0
